server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: never

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiry: 1800000
  refresh-token-expiry: 2592000000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace